name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.1.4
#  - pip=20.3.3
  - mlflow=1.14.1
  - scikit-learn=0.24.1
#  - matplotlib=3.2.2
  - matplotlib
  - pillow=8.1.2
  - wandb=0.12.1
#  - pip:
#      - wandb==0.10.21
