name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=20.3.3
  - requests
  - mlflow=1.14.1
  - wandb=0.12.1
  - pip:
      - git+https://github.com/bwassim/ML-pipeline-rental-NYC.git#egg=wandb-utils&subdirectory=components
#      - git+https://github.com/bwassim/ML-pipeline-rental-prices-NYC#egg=wandb-utils&subdirectory=components
