name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=20.3.3
  - requests
  - mlflow=1.14.1
  - wandb=0.12.1
  - pip:
#      - wandb==0.10.31
      - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
#      - git+https://github.com/bwassim/ML-pipeline-rental-prices-NYC#egg=wandb-utils&subdirectory=components
